modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"

[[mods]]
modId="salwayseat"
version="${file.jarVersion}"
displayName="AlwaysEat"
dateJSONURL="https://raw.githubusercontent.com/suppergerrie2/AlwaysEat/master/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/alwayseat"
#logoFile="AlwaysEat.png"
authors="suppergerrie2"
description='''
Makes all food eatable even when you are full
'''
